### ISSUE TITLE
How can I get the regressor matrix of a robot?

### ISSUE THREAD

**Issue by hsqthu2012** [cdsousa/SymPyBotics#20]
Hi, it is a great work!
But I am trying to get the regressor matrix of a robot and I use: `rbt.Hb_code` and `rbt.H_code`. The resulting output is `([(x0, \ddot{q}_1),
  (x1, 50*\ddot{q}_1),
  (x2, -\dot{q}_2),
  (x3, cos(q2)),
  (x4, \dot{q}_1),
  (x5, x3*x4),
  (x6, x2*x5),
  (x7, sin(q2)),
  (x8, -x3),
  (x9, x4*x7),
  (x10, x2*x9),
  (x11, x0*x3 + x10),
  (x12, -x2),
  (x13, x12*x5),
  (x14, x0*x7),
  (x15, x13 + x14),
  (x16, x10 + x11),
  (x17, -x7),
  (x18, x16*x17),
  (x19, -\ddot{q}_2),
  (x20, x5*x9),
  (x21, x19 + x20),
  (x22, x2**2),...`
I am not quite understand the meaning of these `x`, they seem not related to the dynamic parameters. So how can I get the right regressor matrix of a robot?

**Comment by cdsousa** [comment]
The `x`s are intermediate variables, as `H_code` is "code" that can be used compute the numeric regressor matrix for numeric inputs. See an example of generating a python function from such code at https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L123 and lines below, and the use of the function at https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L156 .  ('C' functions are also available, see https://github.com/cdsousa/SymPyBotics/blob/master/README.md)

This is done this way, rather than using a symbolic matrix, since such matrices are gigantic for medium/large sized robots.

**Comment by ShawnSong1993** [comment]
> The `x`s are intermediate variables, as `H_code` is "code" that can be used compute the numeric regressor matrix for numeric inputs. See an example of generating a python function from such code at https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L123 and lines below, and the use of the function at https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L156 . ('C' functions are also available, see https://github.com/cdsousa/SymPyBotics/blob/master/README.md)
> 
> This is done this way, rather than using a symbolic matrix, since such matrices are gigantic for medium/large sized robots.
is this equation right?   Torque = Hb_code * rbt.dyn.baseparms
