### ISSUE TITLE
Generate Direct Dynamics C Code

### ISSUE THREAD

**Issue by kosari** [cdsousa/SymPyBotics#9]
Does this package generate direct dynamics c code? 

I was able to get inv_dyn but would like to have a function that takes (q, qdot , tau) and calculates qdotdot.

**Comment by moorepants** [comment]
I'm not sure if this package does forward dynamics but we do over at PyDy and SymPy:

https://github.com/pydy/pydy

**Comment by cdsousa** [comment]
Thank you @moorepants for the reply. Only now I saw the issue. It's a shame why do GitHub doesn't automatically makes the repo owners also their watchers...

SymPyBotics generates dynamic terms code which can be used to compute the direct dynamics (qdotdot = M^-1 (tau - h(q, qdot))), but it doesn't generate the code directly.

PyDy, while more general, can be an option in the long term since I lacking time to maintain this package (I was supposed to start contributing to PyDy in the past).
